"""Added summary field

Revision ID: 324eee184569
Revises: 53c41a1c8cf7
Create Date: 2014-10-16 12:08:32.988980

"""

# revision identifiers, used by Alembic.
revision = '324eee184569'
down_revision = '53c41a1c8cf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    ### end Alembic commands ###
