"""Added summary field

Revision ID: 4a1315ecb9d3
Revises: None
Create Date: 2014-10-16 13:37:22.196620

"""

# revision identifiers, used by Alembic.
revision = '4a1315ecb9d3'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    ### end Alembic commands ###
